guitarpages/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('practice.urls'))
]

practice/urls.py
from django.urls import path

from . import views
from . import components

urlpatterns = [
    path('', views.index, name='index'),
    path('exercises', views.exercises, name='exercises'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('register', views.register, name='register'),
    path('user/<int:id>', views.user, name='user'),
    path('record/<int:id>', views.record, name='record'),
    path('routine/new', views.new_routine, name='new_routine'),
    path('exercise/new', views.new_exercise, name='new_exercise'),
    path('exercise/edit/<int:id>', views.edit_exercise, name='edit_exercise'),
    path('exercise/<int:id>', views.exercise_view, name='exercise'),

    path('components/add_exercise', components.add_exercise, name='component_add_exercise'),
    path('components/new_exercise', components.new_exercise_form, name='component_new_exercise')
]

practice/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, related_name='profile', on_delete=models.CASCADE)

#######################
# EXERCISE PROPERTIES #
#######################

class Type(models.Model):
    name = models.CharField(max_length=64, null=False)

    def __str__(self):
        return self.name
    
class Measurement(models.Model):
    name = models.CharField(max_length=64, null=False)

    def __str__(self):
        return self.name

class Skill(models.Model):
    name = models.CharField(max_length=64, null=False)

    def __str__(self):
        return self.name

class Exercise(models.Model):
    
    class Privacy(models.TextChoices):
        PRIV = 'PV', 'Private'
        PUBLIC = 'PB', 'Public'
        UNLISTED = 'UL', 'Unlisted'
    
    name = models.CharField(max_length=100, null=False)
    type = models.ForeignKey(Type, null=True, on_delete=models.SET_NULL, related_name='exercises')
    quality_measurement = models.ForeignKey(Measurement, null=True, on_delete=models.SET_NULL, related_name='exercises')
    description = models.CharField(max_length=500, blank=True, null=True)
    skills = models.ManyToManyField(Skill, blank=True, related_name='exercises')
    video_link = models.CharField(max_length=64, blank=True, null=True)
    creator = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, related_name='exercises')
    privacy = models.CharField(max_length=2, choices=Privacy.choices, default="PV")

    def __str__(self):
        return self.name

####################
# PRACTICE ROUTINE #
####################

class Routine(models.Model):

    class Privacy(models.TextChoices):
        PRIV = 'PV', 'Private'
        PUBLIC = 'PB', 'Public'
        UNLISTED = 'UL', 'Unlisted'
    
    name = models.CharField(max_length=100, null=False)
    creator = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, related_name='routines')
    privacy = models.CharField(max_length=2, choices=Privacy.choices, default="PV")
    description = models.CharField(max_length=500, blank=True, null=True)
    skills = models.ManyToManyField(Skill, blank=True, related_name='routines')


class RoutineExercise(models.Model):
    routine = models.ForeignKey(Routine, related_name='exercises', on_delete=models.CASCADE)
    exercise = models.ForeignKey(Exercise, related_name='routines', on_delete=models.CASCADE)
    length = models.IntegerField()

###########
# RECORDS #
###########

class RoutineRecord(models.Model):
    routine = models.ForeignKey(Routine, on_delete=models.CASCADE, related_name='records')
    time = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, related_name='routine_records', on_delete=models.CASCADE)


class Record(models.Model):
    exercise = models.ForeignKey(Exercise, related_name='records', on_delete=models.CASCADE)
    time = models.DateTimeField(auto_now_add=True)
    note = models.CharField(max_length=512, null=True, blank=True)
    quality_rating = models.IntegerField()
    length = models.IntegerField()
    user = models.ForeignKey(User, related_name='records', on_delete=models.CASCADE)
    routine_record = models.ForeignKey(RoutineRecord, related_name='sub_records', on_delete=models.CASCADE, null=True, default=None)

practice/forms.py
from django import forms
from .models import Exercise, Record, Routine

################
# ExerciseForm #
################

class ExerciseForm(forms.ModelForm):

    description = forms.CharField(widget=forms.Textarea(attrs={"placeholder": "Describe the exercise..."}), required=False)

    class Meta:
        model = Exercise
        fields = ['name', 'type', 'quality_measurement', 'description', 'skills', 'video_link', 'privacy']


##############
# RecordForm #
##############

class RecordForm(forms.ModelForm):

    note = forms.CharField(widget=forms.Textarea(attrs={'rows': '4'}), required=False)

    class Meta:
        model = Record
        fields = ['note', 'quality_rating', 'length']


###############
# RoutineForm #
###############

class RoutineForm(forms.ModelForm):

    description = forms.CharField(widget=forms.Textarea(attrs={"placeholder": "Describe the routine..."}), required=False)

    class Meta:
        model = Routine
        fields = ['name', 'description', 'skills', 'privacy']

practice/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django import forms
from django.urls import reverse
from django.db.models import Q, Value, F, Func, CharField
from django.db import IntegrityError

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from django.contrib.auth.models import User
from .models import Exercise, Record, RoutineExercise, Routine
from .forms import ExerciseForm, RecordForm, RoutineForm

# Create your views here.
def index(request):
    return render(request, 'practice/index.html')

#######################
# USER AUTHENTICATION #
#######################

def login_view(request):

    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('index'))
        else:
            return render(request, 'practice/login.html', {
                'message': 'Username or password is incorrect'
            })
    else:
        return render(request, 'practice/login.html')

@login_required
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        confirmation = request.POST['confirmation']

        if password != confirmation:
            return render(request, 'practice/register.html', {
                'error': "Passwords do not match"
            })
        
        try:
            user = User.objects.create_user(username, None, password)
            user.save
        except IntegrityError:
            return render(request, 'practice/register.html', {
                'error': 'Username is already taken'
            })

        login(request, user)
        return HttpResponseRedirect(reverse('index'))

    return render(request, 'practice/register.html')

def user(request, id):
    return HttpResponse(User.objects.get(id=id))

#############
# EXERCISES #
#############

@login_required
def new_exercise(request):
    if request.method == "POST":
        form = ExerciseForm(request.POST)
        if form.is_valid():
            form.instance.creator = request.user
            form.save()
            return HttpResponseRedirect(reverse('exercise', kwargs={'id': form.instance.id}))
    
    return render(request, 'practice/new_exercise.html', {
        'form': ExerciseForm(),
        'action': "Create"
    })

@login_required
def edit_exercise(request, id):
    exercise = Exercise.objects.get(id=id)
    if exercise.creator == request.user:
        if request.method == "POST":
            form = ExerciseForm(request.POST, instance=exercise)
            if form.is_valid():
                form.save()
                return HttpResponseRedirect(reverse('exercise', kwargs={'id': id}))
            else:
                return render(request, 'practice/new_exercise.html', {
                    'form': form,
                    'action': 'Edit'
                })

        else:
            return render(request, 'practice/new_exercise.html', {
                "form": ExerciseForm(instance=Exercise.objects.get(id=id)),
                'action': 'Edit'
            })
    

def exercise_view(request, id):
    exercise = Exercise.objects.filter(id=id).first()

    if request.user.is_authenticated:
        records = exercise.records.filter(user=request.user.id).order_by('-time')
    else:
        records = None

    if exercise and (request.user.is_authenticated and exercise.creator == request.user) or exercise.privacy == "PB" or exercise.privacy == "UL":
        return render(request, 'practice/exercise.html', {
            'exercise': exercise,
            'records': records
        })

def exercises(request):
    if request.user.is_authenticated:
        exercises = Exercise.objects.filter(Q(creator=request.user) | Q(privacy='PB'))
    else:
        exercises = Exercise.objects.filter(privacy='PB')

    return render(request, 'practice/exercises.html', {
        'exercises': exercises
    })

###################
# RECORD EXERCISE #
###################

def record(request, id):
    exercise = Exercise.objects.filter(id=id).first()
    if exercise:
        
        if request.method == 'POST':
            record = RecordForm(request.POST)
            if record.is_valid():
                record.instance.exercise = exercise
                record.instance.user = request.user
                record.save()

                return HttpResponseRedirect(reverse('exercise', kwargs={'id': id}))

        return render(request, 'practice/record.html', {
            'exercise': exercise,
            'form': RecordForm()
        })
    

#####################
# PRACTICE ROUTINES #
#####################

def new_routine(request):

    # New routine template will have title, description, skills, privacy

    # After this, "Add exercise" button will use Javascript and "add_exercise" template to add a new exercise

    # Clicking submit on this form will append RoutineExercise information to a list and use the use the "added_exercise"
    # to add it to the routine's list of exercise

    # You should be able to remove any of these exercises.

    # The final submit button should POST request a new routine to this view, then POST each individual RoutineExercise

    return render(request, 'practice/new_routine.html', {
        "form": RoutineForm(auto_id="routine_%s")
    })

practice/templates/practice/exercise.html
{% extends 'practice/layout.html' %}

{% block body %}
    <h1>{{ exercise.name }}</h1>
    <h2>{{ exercise.type }}</h2>
    <p>Posted by: <a class="no-link" href="{% url 'user' exercise.creator.id %}">{{ exercise.creator }}</a></p>
    {% if exercise.video_link %}
        <iframe id='record-video' width="560" height="315" src="{{ exercise.video_link }}" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
    {% endif %}
    <p>{{ exercise.description }}</p>
    <a href="{% url 'record' exercise.id %}"><button>Record</button></a>
    {% if request.user == exercise.creator %}
        <a href="{% url 'edit_exercise' exercise.id %}"><button>Edit</button></a>
    {% endif %}

    {% if request.user.is_authenticated %}
        <h1>Exercise History</h1>
        <table class="record-table">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Note</th>
                    <th>Length</th>
                    <th>{{ exercise.quality_measurement }}</th>
                </tr>
            </thead>
            <tbody>
                {% for record in records %}
                    <tr>
                        <td>{{ record.time|date:"m/d/y" }}</td>
                        <td>{{ record.note }}</td>
                        <td>{{ record.length }} minutes</td>
                        <td>{{ record.quality_rating }} {{ exercise.quality_measurement }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {% if records|length == 0 %}
            <p><b>You have not recorded this exercise.</b></p>
        {% endif %}
        <div style="height: 300px;"></div>
    {% endif %}
{% endblock %}

practice/templates/practice/exercises.html
{% extends 'practice/layout.html' %}

{% block body %}
    {% for exercise in exercises %}
        <h1>{{ exercise.name }}</h1>
        <h3>{{ exercise.type }}</h3>
        <p>{{ exercise.description }}</p>
        <a href="{% url 'exercise' exercise.id %}"><button>View</button></a>
        <a href="{% url 'record' exercise.id %}"><button>Record</button></a>
        {% if exercise.creator == request.user %}
            <a href="{% url 'edit_exercise' exercise.id %}"><button>Edit</button></a>
        {% endif %}
    {% endfor %}
{% endblock %}

practice/templates/practice/index.html
{% extends 'practice/layout.html' %}

{% block body %}
    {% if request.user.is_authenticated %}
        <a href="{% url 'new_exercise' %}"><button>Create New Exercise</button></a>
    {% endif %}
    <a href="{% url 'exercises' %}"><button>View Exercises</button></a>
{% endblock %}

practice/templates/practice/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'practice/styles.css' %}">
    <title>Guitar Pages</title>
    {% block header %}
    {% endblock %}
</head>
<body>
    <header id="header">
        <nav id="navbar">
            <ul>
                <h3><a class="no-link" href="{% url 'index' %}">GuitarPages</a></h3>
                {% if request.user.is_authenticated %}
                    <li>
                        <a class='no-link' href="{% url 'exercises' %}">Exercises</a>
                    </li>
                    <li>
                        Routines
                    </li>
                    <li>
                        <a class='no-link' href="{% url 'logout' %}">Log Out</a>
                    </li>
                {% else %}
                    <li>
                        <a class='no-link' href="{% url 'login' %}">Log In</a>
                    </li>
                    <li>
                        <a class="no-link" href="{% url 'register' %}">Register</a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    </header>
    <main>
        <div id="body">
            {% block body %}
            {% endblock %}
        </div>
    </main>
</body>
</html>

practice/templates/practice/login.html
{% extends 'practice/layout.html' %}

{% block body %}
    <h1>Log In</h1>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <input autofocus type="text" placeholder="Username" name="username">
        <input type="password" placeholder="Password" name="password">
        <input type="submit">
    </form>
{% endblock %}

practice/templates/practice/new_exercise.html
{% extends 'practice/layout.html' %}

{% block body %}
    <h1 class="form-heading">{{ action }} Exercise</h1>
    <form id="new-exercise-form" action="{% if action == 'Create' %}{% url 'new_exercise' %}{% else %}{% url 'edit_exercise' form.instance.id %}{% endif %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input id="new-exercise-create" type="submit" value="{{ action }}">
    </form>
{% endblock %}

practice/templates/practice/new_routine.html
{% extends "practice/layout.html" %}

{% load static %}

{% block header %}
    <script src="{% static 'practice/new-routine.js' %}"></script>
{% endblock %}

{% block body %}

    <h1 class="form-heading">Create Routine</h1>
    <div id="new-routine-form">
        {% csrf_token %}
        {{ form }}
        <div id="added-exercise-div">
        </div>
        <button id="add-new-exercise">Add New Exercise</button>
        <button id="add-existing-exercise">Add Existing Exercise</button>
        <div id="add-exercise-div">
        </div>
        <input id="new-routine-create" type="submit">
    </div>

{% endblock %}

practice/templates/practice/record.html
{% extends 'practice/layout.html' %}

{% block body %}
    <h1>Record {{ exercise.name }}</h1>
    <form id="record-form" action="{% url 'record' exercise.id %}" method="post">
        {% csrf_token %}

        <label for="id_note">Note:</label>
        {{ form.note }}
        <label for="id_quality_rating">{{ exercise.quality_measurement }}{% if exercise.quality_measurement.name == 'Quality' %} (1-5){% endif %}:</label>
        {{ form.quality_rating }}
        <label for="id_length">Length (mins):</label>
        {{ form.length }}
        
        <input id='record-submit' type="submit">
    </form>
{% endblock %}

practice/templates/practice/register.html
{% extends 'practice/layout.html' %}

{% block body %}
    <h1>Register</h1>
    <form action="{% url 'register' %}" method="post">
        {% csrf_token %}

        <p>
            <label for="register_username">Username:</label>
            <input id="register_username" type='text' name="username" placeholder="Username">
        </p>
        
        <p>
            <label for="register_password">Password:</label>
            <input id="register_password" type="password" name="password" placeholder="Password">
        </p>

        <p>
            <label for="register_confirmation">Confirm Password:</label>
            <input id="register_confirmation" type="password" name="confirmation" placeholder="Confirm Password">
        </p>
        <input type="submit" value="Register">
    </form>
{% endblock %}